// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUAc28wt7R_6KyCn58fPGB80DY5ekTv9o',
    appId: '1:230761275611:web:90e66d1463abe9b5422cfe',
    messagingSenderId: '230761275611',
    projectId: 'all-events-25739',
    authDomain: 'all-events-25739.firebaseapp.com',
    storageBucket: 'all-events-25739.firebasestorage.app',
    measurementId: 'G-6QPS1CWD6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo4Yo7tZjr2NXi9hWXqLNIlRpqaoTvN4E',
    appId: '1:230761275611:android:cfa8a941cef50b44422cfe',
    messagingSenderId: '230761275611',
    projectId: 'all-events-25739',
    storageBucket: 'all-events-25739.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApXfFtMlRuHHAEeoExjDIUi5G5lYXaKtM',
    appId: '1:230761275611:ios:510173256a1931f0422cfe',
    messagingSenderId: '230761275611',
    projectId: 'all-events-25739',
    storageBucket: 'all-events-25739.firebasestorage.app',
    iosClientId:
        '230761275611-0v8dgu96orvf1c897m5lq9b8avut1de9.apps.googleusercontent.com',
    iosBundleId: 'com.example.allEventsTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApXfFtMlRuHHAEeoExjDIUi5G5lYXaKtM',
    appId: '1:230761275611:ios:510173256a1931f0422cfe',
    messagingSenderId: '230761275611',
    projectId: 'all-events-25739',
    storageBucket: 'all-events-25739.firebasestorage.app',
    iosClientId:
        '230761275611-0v8dgu96orvf1c897m5lq9b8avut1de9.apps.googleusercontent.com',
    iosBundleId: 'com.example.allEventsTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUAc28wt7R_6KyCn58fPGB80DY5ekTv9o',
    appId: '1:230761275611:web:1553c9cc211149f1422cfe',
    messagingSenderId: '230761275611',
    projectId: 'all-events-25739',
    authDomain: 'all-events-25739.firebaseapp.com',
    storageBucket: 'all-events-25739.firebasestorage.app',
    measurementId: 'G-RHE6SCM59K',
  );
}
